project:
  type: website
  output-dir: docs

# ~additional metadata excluded for brevity ~
website:
  navbar:
    title: "Jayne Campbell"
    left:
      - href: index.qmd
        text: Home
      - href: internships.qmd
        text: Internships
      - href: researchpapers.qmd
        text: Research Papers
      - photography.qmd
      - href: digitals.qmd
        text: Digitals
  page-footer:
    background: light
    left: Copyright 2024, Jayne Campbell
    right: This website is built with {{< fa heart title="a heart" >}}
    

format:
  html:
    theme: 
      light: minty
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full

editor: visual
