project:
  type: website
  output-dir: docs

# ~additional metadata excluded for brevity ~
website:
  navbar:
    title: "Jayne Campbell"
    left:
      - href: index.qmd
        text: Home
      - internships.qmd
      - photography.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

