---
title: "Internships and Research Experience"
---

**INTERNSHIP EXPERIENCE**

**Research Assistant for Froehlich lab**   Mar 2024 – Jun 2024

Project: Climate training giant kelp

-   Assisted in testing an early intervention, low-cost heatwave conditioning treatment for giant kelp in an aquaculture setting

-   Participated in experimental set up, break-down, data collection, and data analysis

-   Analyzed images using ImageJ and Trigit 

-   Visualized data using R and Rstudio to create graphs and figures 

**Marine Conservation Intern**   Aug 2022 – Sep 2022

Whale Shark and Oceanic Research Center, Utila, Honduras

-   Completed Caribbean marine organism identification workshops with examination of Caribbean reef fish, reef-associated organisms, and corals

-   Collected data on international citizen science databases for the Reef Environmental Education Foundation

-   Monitored and cleaned coral nurseries and conducted invasive Lionfish species removal, dissection, and data collection

-   Conducted reef survey dives using the Atlantic and Gulf Rapid Reef Assessment methodology to evaluate reef health, treating dive sites against the Stony Coral Tissue Loss Disease

-   Successfully proposed, developed, and presented a personal project to the organization within four weeks that centered on providing future interns with tools to assist with classifying fish species during reef surveys 

**Early Childhood Environmental Education Intern** Apr 2022 – Jun 2022

Kids in Nature Program, UCSB

-   Promoted the aspirations and achievements of students in underserved schools in Goleta 

-   Provided quality environmental science education and experiences through field trips and nature walks

-   Educated students about the local flora and fauna that was observed

**Restoration Ecology Intern** 					    Feb 2022 – Apr 2022

Cheadle Center for Biodiversity and Ecological Restoration, UCSB

-   Learned the process of restoration site design, implementation, and maintenance techniques

-   Cultivated and identified native plants at the restoration sites 

-   Conducted seed collection and ecological monitoring protocols

-   Eradicated invasive plants to protect sensitive native plants, with special attention to vernal pool habitats
